export type Category =
  | 'inspiration'
  | 'developer'
  | 'funny'
  | 'stoic'
  | 'movies'
  | 'knowledge'
  | 'motivation'
  | 'finance'
  | 'relationship'
  | 'design'
  | 'human'
  | 'captions'
  | 'social'
  | 'custom';

export type Quote = { id: string; text: string; author: string; category: Category };

export const CATEGORY_LABEL: Record<Category, string> = {
  inspiration: 'Inspiration',
  developer: 'Developer',
  funny: 'Funny',
  stoic: 'Stoic',
  movies: 'Movies',
  knowledge: 'Knowledge',
  motivation: 'Motivation',
  finance: 'Finance',
  relationship: 'Relationship',
  design: 'Design',
  human: 'Human nature',
  captions: 'Captions',
  social: 'Social',
  custom: 'Custom',
};

// derived from the labels so a new category cannot be added in one place and missed in the other
export const ALL_CATEGORIES = Object.keys(CATEGORY_LABEL) as Category[];

const RAW: [Category, string, string][] = [
  ['developer', 'First, solve the problem. Then, write the code.', 'John Johnson'],
  ['developer', 'Programs must be written for people to read, and only incidentally for machines to execute.', 'Harold Abelson'],
  ['developer', 'Simplicity is prerequisite for reliability.', 'Edsger W. Dijkstra'],
  ['developer', 'Make it work, make it right, make it fast.', 'Kent Beck'],
  ['developer', 'The cheapest, fastest and most reliable components are those that aren’t there.', 'Gordon Bell'],
  ['developer', 'Premature optimization is the root of all evil.', 'Donald Knuth'],
  ['developer', 'Deleted code is debugged code.', 'Jeff Sickel'],

  ['inspiration', 'The best way out is always through.', 'Robert Frost'],
  ['inspiration', 'What we do now echoes in eternity.', 'Marcus Aurelius'],
  ['inspiration', 'It always seems impossible until it’s done.', 'Nelson Mandela'],
  ['inspiration', 'Whether you think you can or you think you can’t, you’re right.', 'Henry Ford'],
  ['inspiration', 'The obstacle is the way.', 'Marcus Aurelius'],
  ['inspiration', 'Fall seven times, stand up eight.', 'Japanese proverb'],

  ['funny', 'I love deadlines. I love the whooshing noise they make as they go by.', 'Douglas Adams'],
  ['funny', 'There are only two hard things in computer science: cache invalidation and naming things.', 'Phil Karlton'],
  ['funny', 'Weeks of coding can save you hours of planning.', 'Unknown'],
  ['funny', 'It works on my machine.', 'Every developer, once'],
  ['funny', 'I’m not lazy, I’m on energy saving mode.', 'Unknown'],
  ['funny', 'A user interface is like a joke. If you have to explain it, it’s not that good.', 'Martin LeBlanc'],

  ['stoic', 'You have power over your mind, not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'],
  ['stoic', 'We suffer more often in imagination than in reality.', 'Seneca'],
  ['stoic', 'No man is free who is not master of himself.', 'Epictetus'],
  ['stoic', 'It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca'],
  ['stoic', 'First say to yourself what you would be; then do what you have to do.', 'Epictetus'],
  ['stoic', 'Waste no more time arguing what a good man should be. Be one.', 'Marcus Aurelius'],

  ['movies', 'Do, or do not. There is no try.', 'Yoda, The Empire Strikes Back'],
  ['movies', 'Roads? Where we’re going we don’t need roads.', 'Doc Brown, Back to the Future'],
  ['movies', 'It’s not who I am underneath, but what I do that defines me.', 'Batman Begins'],
  ['movies', 'Every man dies. Not every man really lives.', 'Braveheart'],
  ['movies', 'The greatest teacher, failure is.', 'Yoda, The Last Jedi'],
  ['movies', 'Why do we fall? So we can learn to pick ourselves up.', 'Batman Begins'],
];

// the collection this player was built for, kept apart from the starter set above
const MINE: [Category, string, string][] = [
  ['motivation', 'You need to understand your default program is run by the past.', ''],
  ['motivation', 'You need to understand how negative emotions create bookmarks to the past and trap you there.', ''],
  ['motivation', 'You need to relearn what meditation is from scratch so you can use it to enter the operating system of your mind.', ''],
  ['motivation', 'You need to commit to not making the same decisions as yesterday and subtly make at least one new uncomfortable decision.', ''],
  ['motivation', 'You need to stop being led in life by the memories of the past and start being led by your vision for the future.', ''],
  ['motivation', 'You need to practice using meditation to develop an awareness of the present. Then when your mind wants to use emotions to escape to the past, you can use present-moment awareness to take back control.', ''],
  ['knowledge', 'Never shake a hand sitting down.', ''],
  ['knowledge', 'Protect who\'s behind you, respect who\'s beside you.', ''],
  ['knowledge', 'Never insult the cooking when you\'re the guest.', ''],
  ['knowledge', 'Never eat the last piece of something you didn\'t buy.', ''],
  ['knowledge', 'Never make the first offer in a negotiation.', ''],
  ['knowledge', 'Don\'t take credit for work you didn\'t do.', ''],
  ['knowledge', 'Take blame, and give credit when due.', ''],
  ['knowledge', 'If you\'re not invited, don\'t ask to go.', ''],
  ['knowledge', 'Don\'t borrow money to buy luxuries.', ''],
  ['knowledge', 'Don\'t lend money to friends you want to keep.', ''],
  ['knowledge', 'Treat credit cards like debit cards.', ''],
  ['knowledge', 'If you can\'t buy it twice, you can\'t afford it.', ''],
  ['knowledge', 'Invest $20 of every $100 you earn.', ''],
  ['knowledge', 'Spend less than you make.', ''],
  ['captions', 'Be not as you are but be as you should be.', ''],
  ['captions', 'With the courage to begin and the discipline to endure, victory becomes a matter of time.', ''],
  ['captions', 'We drink the poison our minds pour for us and wonder why we feel so sick.', 'Atticus'],
  ['captions', 'Why should I fear death? If I am, death is not. If death is, I am not. Why should I fear that which cannot exist when I do?', ''],
  ['captions', 'If you\'re in the forest and you walk past the same tree twice, you\'re lost.', ''],
  ['captions', 'The giant in front of you is never bigger than the God inside of you.', '1 John 4:4'],
  ['captions', 'Don\'t waste your time chasing butterflies. Mend your garden, and they will come.', ''],
  ['captions', 'Maturing is realising "punishable with a fine" really means legal with a price.', ''],
  ['captions', 'Nobody is stronger than a broken man who rebuilt himself.', ''],
  ['captions', 'The game only ends when the king has fallen, not when a pawn takes your queen.', ''],
  ['captions', '"At least I tried" is far better than "what if I tried?"', ''],
  ['captions', 'Everybody wants a quick fix. You may see some results, but they won\'t be permanent. The permanent results come from having to suffer.', ''],
  ['captions', 'Do you know why hugs are so beautiful? The right side of you does not have a heart, so it is empty, and when you hug you have a heart on both sides.', ''],
  ['captions', 'Humble enough to know I can lose it all. Confident enough to know I can get it all back.', ''],
  ['captions', 'Know your worth. You must find the courage to leave the table if respect is no longer being served.', ''],
  ['captions', 'Most people mess up something good by looking for something better, just to end up with something worse.', ''],
  ['captions', 'Being single with high standards is better than settling for less.', ''],
  ['captions', 'Time passes, memories fade, feelings change, people leave, but hearts never forget.', ''],
  ['captions', 'Even though I walk through the darkest valley I fear no evil, for you are with me.', ''],
  ['captions', 'No one can understand you when you have water on your hands and dryness in your chest, when survival is in your body and drowning is in your heart, when light is around you and darkness is inside you.', ''],
  ['captions', 'It is not enough that I should succeed - others should fail.', 'Gore Vidal'],
  ['captions', 'Close the windows that hurt you, no matter how beautiful the view is.', ''],
  ['captions', 'No one will know the violence it took to become this gentle.', ''],
  ['captions', 'Power flows to the one who knows how. Desire alone is not enough.', 'Megatron'],
  ['captions', 'In life the road to darkness is a journey, not a light switch.', 'Lex Luthor'],
  ['captions', 'Every choice you have made has led you to this moment.', 'Darth Maul'],
  ['captions', 'You miss 100% of the shots you don\'t take.', 'Deadshot'],
  ['captions', 'A woman that can be bought isn\'t worth having.', 'Kingpin'],
  ['captions', 'The one thing they love more than a hero is to see a hero fail. In spite of everything you\'ve done for them, eventually they will hate you.', 'Green Goblin'],
  ['captions', 'I know what it\'s like to lose. To feel so desperately that you\'re right, yet to fail nonetheless. It\'s frightening.', 'Thanos'],
  ['captions', 'You either die a hero or you live long enough to see yourself become the villain.', 'Harvey Dent'],
  ['captions', 'It\'s easy to fool people when they are already fooling themselves.', 'Mysterio'],
  ['captions', 'Not every problem has a solution.', ''],
  ['captions', 'The day a mosquito lands on your testicles is the day you will know that violence is not always the answer.', ''],
  ['captions', 'Learn to be alone, because nobody stays forever.', 'Joker'],
  ['captions', 'Sometimes they don\'t love you, they only love the way you love them.', 'Joker'],
  ['captions', 'Be a better man. Be a better dad. Be a better son. This is the masculine way.', ''],
  ['captions', 'When you buy a new car, make sure it\'s better than your last.', ''],
  ['captions', 'Use the 9-5 to fund a 5-9. Once built, use the 5-9 to fund the 24/7.', ''],
  ['captions', 'You can\'t keep blaming yourself. Just blame yourself once and move on.', 'Homer Simpson'],
  ['captions', 'How lucky I am to have something that makes saying goodbye so hard.', 'Winnie the Pooh'],
  ['captions', 'Don\'t go out partying when you have nothing to celebrate.', ''],
  ['captions', 'Respect all. Fear no one.', ''],
  ['captions', 'More moves. Less announcements.', ''],
  ['captions', 'Obstacles aren\'t here to block you. They are here to see how badly you want it.', ''],
  ['captions', 'When you\'re the ocean, you don\'t have to be afraid of the waves.', ''],
  ['captions', 'Socialising is a skill like any other. You need to practise before you\'re good at it.', ''],
  ['captions', 'Resentment is like taking poison and waiting for the other person to die.', ''],
  ['captions', 'Not everything is a lesson. Sometimes you just fail.', ''],
  ['captions', 'Accept your pain, but do not accept that you deserved it.', ''],
  ['captions', 'What is the most important step a man can take? Always the next step.', ''],
  ['captions', 'Sucking at something is the first step to being sort of good at something.', ''],
  ['captions', 'Death is not the greatest loss in life. The greatest loss is what dies inside us while we live.', ''],
  ['captions', 'Don\'t waste your time chasing butterflies. Mend your garden, and the butterflies will come.', ''],
  ['captions', 'Careful who you trust. The devil was once an angel.', ''],
  ['captions', 'The man who moves a mountain begins by carrying away small stones.', ''],
  ['captions', 'If the plan doesn\'t work, change the plan but never the goal.', ''],
  ['captions', 'Be not afraid of going slowly, be afraid only of standing still.', ''],
  ['captions', 'Work while they sleep. Learn while they party. Save while they spend. Live like they dream.', ''],
  ['captions', 'He who refuses to give his all will achieve and receive nothing.', ''],
  ['captions', 'Forgiving them is your gift to them. Moving on is your gift to yourself.', ''],
  ['captions', 'You can\'t fix broken glass without hurting yourself.', ''],
  ['captions', 'Your future is the result of your daily actions. You\'re defined by what you do today.', ''],
  ['captions', 'The impossible happens to those who try.', ''],
  ['captions', 'Happiness is not having what you want, but wanting what you have.', ''],
  ['captions', 'Do it for the people who want to see you fail.', ''],
  ['captions', 'If you are a friend of everybody, you are an enemy to yourself.', ''],
  ['captions', 'Sometimes when you are in a dark place you think you have been buried, but actually you have been planted.', ''],
  ['captions', 'Once the rain is over, an umbrella becomes a burden. That\'s how loyalty ends when benefits stop.', ''],
  ['captions', 'When one door closes another opens, but we often look so long and so regretfully upon the closed door that we do not see the one that has opened for us.', ''],
  ['captions', 'Always look for the fool in the deal. If you don\'t find one, it\'s you.', ''],
  ['captions', 'The ability to observe without evaluating is the highest form of intelligence.', ''],
  ['captions', 'Can a person be happy if they have never experienced sadness?', ''],
  ['captions', 'Learn to change, change to learn. Adapt to change, and change to adapt.', ''],
  ['captions', 'Do we have the power to alter our minds and personality, or does the mind determine who we are?', ''],
  ['captions', 'Can life without love exist?', ''],
  ['captions', 'Would you really want to live a life free of challenges or obstacles?', ''],
  ['captions', 'Is love a choice, or a feeling you can\'t control?', ''],
  ['social', 'She\'s a red flag but I need character development.', ''],
  ['social', 'While waiting for the right one, have fun with the wrong ones.', ''],
  ['social', 'This is the greener grass they were talking about.', ''],
  ['social', 'You started a new chapter, but I wrote the book.', ''],
  ['social', 'Truth be told, you were not the only one.', ''],
  ['social', 'You miss me? Nah, you just failed to replace me.', ''],
  ['social', 'The bar is so low and you still can\'t reach it.', ''],
  ['social', 'Remember when I thought you were interesting.', ''],
  ['social', 'Wait, you thought this was serious?', ''],
  ['social', 'Tied my shoes, I\'m done tripping.', ''],
  ['social', 'Often imitated, never duplicated.', ''],
  ['social', 'Praying for my downfall doesn\'t make you religious.', ''],
  ['social', 'Got bad habits but good intentions.', ''],
  ['social', 'My name has touched rooms I\'ll never walk into.', ''],
  ['social', 'The grass doesn\'t get any greener.', ''],
  ['social', 'Same game, different level.', ''],
  ['social', 'Everyone\'s got their hands out, but not to reach me.', ''],
  ['social', 'Real eyes realise real lies.', ''],
  ['social', 'If they ghost you, respect the dead and never disturb them again.', ''],
  ['social', 'They\'re swiping up on someone else\'s note. Focus on yourself.', ''],
  ['social', 'Life is short, spend it with me.', ''],
  ['social', 'Who said I need you? I want you.', ''],
  ['social', 'GPS said you missed a turn. Come back.', ''],
  ['social', 'All these notes are taken, you and I aren\'t.', ''],
  ['social', 'Jan, Feb, Mar, Apr, May I take you out.', ''],
  ['social', 'Never in your likes, always in my views.', ''],
  ['social', 'Walking wish list.', ''],
  ['social', 'Not heartless, just doing my heart less.', ''],
  ['social', 'Down to earth but still above you.', ''],
  ['social', 'I wasn\'t playing cards but somehow I pulled a queen.', ''],
  ['social', 'Not really into talking unless the outcome is income.', ''],
  ['social', 'Don\'t look at the caption, look at me.', ''],
  ['social', 'Dreams mean nothing if you leave them on your pillow.', ''],
  ['social', 'Feeling myself like I lost my keys.', ''],
  ['social', 'We couldn\'t connect, there was no signal.', ''],
  ['social', 'Heaven sent but she\'s fine as hell.', ''],
  ['social', 'She\'s a walking red flag, but I\'m colour blind.', ''],
  ['social', 'Money talks, wealth whispers.', ''],
  ['social', 'Impact, not impress.', ''],
  ['social', 'Underrated is an understatement.', ''],
  ['social', 'In touch but out of reach.', ''],
  ['social', 'Broke her heart into paragraphs.', ''],
  ['social', 'She thinks she\'s a player but I\'m player two.', ''],
  ['social', 'Said I was too much, so you settled for less.', ''],
  ['social', 'Put you in a win-win situation and you still lost.', ''],
  ['social', 'Flirt with many, but love none.', ''],
  ['knowledge', 'Desire is a contract that you make with yourself to be unhappy until you get what you want.', ''],
  ['knowledge', 'We have two lives, and the second begins when you realize we only have one', 'Confucius'],
  ['knowledge', 'Finishing a book is easy. Understanding it is harder.', ''],
  ['knowledge', 'More the knowledge, lesser the ego. Lesser the knowledge, more the ego.', 'Albert Einstein'],
  ['knowledge', 'The most useful insights are often found at the intersection of ideas.', ''],
  ['knowledge', 'Discipline is doing what you hate to do, but nonetheless doing it like you love it.', ''],
  ['knowledge', 'Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.', ''],
  ['knowledge', 'I have the recipes but not the ingredients.', 'Dave Chappelle'],
  ['knowledge', 'All the breaks you need in life wait within your imagination.', 'Napoleon Hill'],
  ['knowledge', 'It is health that is the real wealth, and not pieces of gold and silver.', 'Mahatma Gandhi'],
  ['knowledge', 'Tell me and I forget, teach me and I may remember, involve me and I learn.', 'Benjamin Franklin'],
  ['knowledge', 'Never pick a fight with someone you are not sure you can defeat.', ''],
  ['knowledge', 'Never let the presence of enemies upset you. You are far better off with a declared opponent or two than not knowing where your real enemies lie.', ''],
  ['knowledge', 'When you see water flowing uphill, it means that someone is repaying a kindness.', ''],
  ['knowledge', 'Such is the fate of him who opens his mouth too much and thereby puts himself at the mercy of the listener.', 'Leonardo da Vinci'],
  ['knowledge', 'I learned that you actually have more power when you shut up.', ''],
  ['knowledge', 'It is easier to cope with a bad conscience than with a bad reputation.', 'Friedrich Nietzsche'],
  ['knowledge', 'Fools say that they learn by experience. I prefer to profit from others\' experiences.', ''],
  ['knowledge', 'When I have laid the bait for deer, I don\'t shoot at the first doe that comes to sniff, but wait until the whole herd has gathered round.', 'Otto von Bismarck'],
  ['knowledge', 'If you can get other people to dig their own graves, why sweat yourself?', ''],
  ['knowledge', 'The question is harder than the answer. If you can properly phrase the question, the answer is the easy part.', ''],
  ['knowledge', 'If you always do what you\'ve always done, you\'ll always get what you\'ve always got.', 'Henry Ford'],
  ['knowledge', 'If you buy books, then actually read them.', ''],
  ['knowledge', 'Amenities in your home don\'t make you rich. The family in the home does.', ''],
  ['knowledge', 'The best way to predict the future is to create it. Not from the known, but from the unknown.', ''],
  ['knowledge', 'It\'s not what we don\'t know that gets us in trouble. It\'s what we know for sure that just ain\'t so.', 'Mark Twain'],
  ['knowledge', 'A villain who despairs of his villainy has not become a hero. A hero is something positive, not just the absence of evil.', ''],
  ['motivation', 'Winning at everything might only mean you\'re not doing anything new or difficult. You might be winning but you\'re not growing, and growing might be the most important form of winning.', ''],
  ['knowledge', 'Insanity is doing the same thing over and over while expecting different results.', ''],
  ['knowledge', 'The present can change the past, and the future can change the present.', 'Jordan Peterson'],
  ['knowledge', 'Sometimes you have to change the way you understand everything to properly understand a single something.', 'Jordan Peterson'],
  ['knowledge', 'You can be pretty smart if you can just shut up.', 'Jordan Peterson'],
  ['motivation', 'You can\'t always choose the path you walk in life, but you can always choose the manner in which you walk it.', 'John O\'Leary'],
  ['motivation', 'Even just a little bit the wrong way is still the wrong way, and will eventually get you to the wrong place.', ''],
  ['motivation', 'The sooner we get it wrong, the sooner we get it right.', ''],
  ['knowledge', 'Don\'t criticise unless you can do better.', 'Don Norman'],
  ['motivation', 'Every decision I made in my life has led me to this.', ''],
  ['motivation', 'Your outer journey may contain a million steps; your inner journey only has one: the step you are taking right now.', 'Eckhart Tolle'],
  ['design', 'A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.', 'Antoine de Saint-Exupery'],
  ['knowledge', 'When people talk, listen completely. Most people never listen.', 'Ernest Hemingway'],
  ['knowledge', 'You think your pain and your heartbreak are unprecedented in the history of the world, but then you read. It was books that taught me that the things that tormented me most were the very things that connected me with all the people who were alive.', 'James Baldwin'],
  ['human', 'Whenever you feel like criticising anyone, just remember that all the people in this world haven\'t had the advantages that you\'ve had.', 'F. Scott Fitzgerald'],
  ['knowledge', 'It\'s through mistakes that you actually grow. You have to get bad in order to get good.', 'Paula Scher'],
  ['knowledge', 'Our bodies have five senses, but not to be overlooked are the senses of our souls: intuition, peace, foresight, trust, empathy.', 'C. JoyBell C.'],
  ['knowledge', 'If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.', 'Nelson Mandela'],
  ['design', 'Only by examining our personal biases can we grow as artists; only by cultivating empathy can we grow as people.', 'Jen Knox'],
  ['design', 'There is no such thing as a boring project. There are only boring executions.', 'Irene Etzkorn'],
  ['knowledge', 'Maths is mental weight training. It is a means to an end, not an end in itself.', 'Chip Heath'],
  ['knowledge', 'The way to learn is by doing.', 'James Clear'],
  ['knowledge', 'There are no busy people, only people who suck at prioritisation.', 'Kunal Shah'],
  ['knowledge', 'Don\'t be a prisoner of your resume. You wrote it to describe your past, not your future.', 'Kunal Shah'],
  ['motivation', 'Results happen over time, not overnight.', ''],
  ['human', 'It\'s easier to win if everybody wants you to win. If you don\'t make enemies out there, it\'s easier to succeed.', 'Randy Komisar'],
  ['motivation', 'Being a giver is not good for a 100-yard dash, but it\'s valuable in a marathon.', 'Chip Conley'],
  ['knowledge', 'The true measure of a man is how he treats someone who can do him absolutely no good.', 'Samuel Johnson'],
  ['knowledge', 'You should be willing to do something that takes you five minutes or less for anybody.', 'Adam Rifkin'],
  ['knowledge', 'If your interactions are ruled by generosity, your rewards will follow suit.', 'Keith Ferrazzi'],
  ['knowledge', 'A good teacher doesn\'t tell you what to do, but shows you how to think and decide for yourself.', ''],
  ['finance', 'Stack your money and act broke. Have more than you show and speak less than you know.', ''],
  ['motivation', 'When you compete against everyone else, no one wants to help you. But when you compete against yourself, everyone wants to help you.', 'Simon Sinek'],
  ['design', 'The more choices users have, the harder it is for them to make one.', ''],
  ['finance', 'Rich people buy luxuries from the money their money made them. Poor people buy luxuries from the sweat of their brow.', ''],
  ['finance', 'Savings without a mission is garbage. Your money needs to work for you, not lie around you.', 'Dave Ramsey'],
  ['finance', 'The rich get richer by continually reinvesting asset profits back into assets.', ''],
  ['finance', 'Buy more money with your money.', ''],
  ['finance', 'Compromise isn\'t a bad word. It\'s the foundation of all relationships, including your relationship with money.', ''],
  ['finance', 'You have achieved financial freedom when you can spend your days doing work you love without worrying about how you will pay the bills.', ''],
  ['finance', 'When you work for money, no matter how much you earn, it will never be enough.', ''],
  ['finance', 'By having money as your ultimate goal you will never be satisfied with what you have today.', ''],
  ['finance', 'If I am doing a job only for the money, then I am working from my limited reserve of willpower alone.', ''],
  ['finance', 'Don\'t think that money does everything, or you will end up doing everything for money.', 'Voltaire'],
  ['finance', 'Wealth is not about having great possessions but about having few needs.', ''],
  ['finance', 'A wise person should have money in their head, but not in their heart.', 'Jonathan Swift'],
  ['finance', 'The number of zeroes at the end of your bank balance is meaningless if you sit at home alone.', ''],
  ['finance', 'Every dollar you spend learning about money is roughly ten dollars you don\'t have to work for in the future.', ''],
  ['finance', 'To secure his fortune he had to waste it. That is strategic generosity: putting wealth to work to win people\'s hearts.', ''],
  ['finance', 'The worth of money is not in its possession, but in its use.', ''],
  ['finance', 'Most people fail to realise that in life it\'s not how much money you make, it\'s how much money you keep.', 'Robert Kiyosaki'],
  ['finance', 'To become wealthy, save first and then spend what\'s left.', 'Darius Foroux'],
  ['finance', 'If you don\'t find a way to make money while you sleep, you will work until you die.', 'Warren Buffett'],
  ['finance', 'The hidden opportunity in your career is fulfilment, not status, money or fame.', 'Tim Denning'],
  ['design', 'Don\'t spend a small effort for a big result. Don\'t spend a big effort for a small result.', 'Chris Do'],
  ['motivation', 'A smooth sea never made a skilled sailor.', 'Franklin D. Roosevelt'],
  ['motivation', 'Good decisions come from experience, and experience often comes from bad decisions.', ''],
  ['motivation', 'Never underestimate the effort twelve months of focus and action can have on the rest of your life.', ''],
  ['motivation', 'People often say that motivation doesn\'t last. Well, neither does bathing, which is why we recommend it daily.', 'Zig Ziglar'],
  ['motivation', 'Without action there is no progress. Without progress there\'s no change. And if nothing changes, you\'re going to get discouraged.', ''],
  ['motivation', 'You wouldn\'t worry so much about what others think of you if you realised how seldom they do.', 'Eleanor Roosevelt'],
  ['motivation', 'Getting stuff done only matters if that stuff actually moves you toward your goals.', ''],
  ['motivation', 'Lord, protect me from my friends; I can take care of my enemies.', ''],
  ['motivation', 'True self-esteem comes from balancing the wants and needs of others with the wants and needs of yourself.', ''],
  ['motivation', 'Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit.', 'E. E. Cummings'],
  ['motivation', 'As soon as you trust yourself, you will know how to live.', 'Johann Wolfgang von Goethe'],
  ['motivation', 'The greatest thing in the world is to know how to belong to oneself.', 'Michel de Montaigne'],
  ['developer', 'Always code as if the person who ends up maintaining your code knows where you live.', 'John Woods'],
  ['motivation', 'The way you frame things in your head can help you push past your perceived limitations.', ''],
  ['motivation', 'He whose life has a why can bear almost any how.', 'Friedrich Nietzsche'],
  ['motivation', 'Don\'t fear failure. Be afraid of not having the chance.', ''],
  ['motivation', 'Don\'t fear failure so much that you refuse to try new things. The saddest summary of a life contains three descriptions: could have, might have, and should have.', 'Louis E. Boone'],
  ['motivation', 'Sometimes you have to run as fast as you can just to stay in the same place.', ''],
  ['motivation', 'You will walk this path alone. You will fight, you will win, you will lose. It\'ll never be perfect, and the journey will end one day, so spend your time wisely here.', ''],
  ['motivation', 'They weren\'t trying to be safe. They were trying to become competent, and it\'s competence that makes people as safe as they can truly be.', 'Jordan Peterson'],
  ['motivation', 'A little bit every single day will get you to your destination. All progress is progress.', ''],
  ['motivation', 'All the greats do one more, and all the average don\'t.', 'Ed Mylett'],
  ['motivation', 'Don\'t give up what you want most for what you want now.', 'Richard G. Scott'],
  ['motivation', 'If I look at the mass, I will never act. If I look at the one, I will.', 'Mother Teresa'],
  ['motivation', 'One of the most important things you can do on this earth is to let people know they are not alone.', 'Shannon L. Alder'],
  ['motivation', 'Only those who attempt the absurd will achieve the impossible.', 'M. C. Escher'],
  ['motivation', 'The source of wisdom is pain.', 'Naval Ravikant'],
  ['motivation', 'Despite our losses, what we gain through grief is profound wisdom.', 'Adrian Drew'],
  ['motivation', 'Every cloud has a silver lining.', ''],
  ['relationship', 'I promised myself I wouldn\'t let you complete me.', ''],
  ['motivation', 'You can\'t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.', 'Steve Jobs'],
  ['relationship', 'Sometimes you just need to distance yourself from certain people.', ''],
  ['motivation', 'It doesn\'t matter if you\'re smart in a world full of stupid people.', ''],
  ['motivation', 'Life is not a race. It doesn\'t matter who finishes first, it matters who enjoys it most.', ''],
  ['motivation', 'If you fear failure, build silently. Privacy is underrated.', ''],
  ['motivation', 'One can have no smaller or greater mastery than mastery of oneself.', 'Leonardo da Vinci'],
  ['motivation', 'Do not think that what is hard for you to master is humanly impossible; and if it is humanly possible, consider it within your reach.', 'Marcus Aurelius'],
  ['motivation', 'Health is wealth.', ''],
  ['relationship', 'You can\'t control what people do to you, but you can control how you react.', ''],
  ['relationship', 'Rejection exists for a reason. It\'s a means to keep apart people who are not good for each other.', ''],
  ['relationship', 'If it comes, it comes. If it goes, let it.', ''],
  ['relationship', 'One day you\'ll wake up at 11:30 on a Sunday with the love of your life, make some coffee and pancakes, and it\'ll all be alright.', ''],
  ['relationship', 'One day that name will not make you smile anymore, and those memories will not make you cry. It will take time, but you will heal.', ''],
  ['relationship', 'How can you call it love if you\'re crying more than smiling?', ''],
  ['relationship', 'A person who has something to prove will move mountains for you.', ''],
  ['relationship', 'Any man who tries to be good all the time is bound to come to ruin among the great number who are not good.', 'Niccolo Machiavelli'],
  ['relationship', 'The better you are at dealing with power, the better friend, lover, husband, wife and person you become.', ''],
  ['relationship', 'The truth is generally seen, rarely heard.', 'Baltasar Gracian'],
  ['relationship', 'Our behaviour is driven by our emotions, so any lasting behaviour change needs an emotional change too.', ''],
  ['relationship', 'What cannot be grasped cannot be consumed.', ''],
  ['relationship', 'What people cannot control, you can control for them.', ''],
  ['relationship', 'If you think that you need more time, you will get more time and more pain. Time and pain are inseparable.', 'Eckhart Tolle'],
  ['relationship', 'No one reaches out to you for compassion so you can teach them how to behave better. They reach out because they believe in your capacity to know your darkness well enough to sit in the dark with them.', 'Brene Brown'],
  ['relationship', 'Don\'t worry about finding the right person. Focus on becoming the right person.', ''],
  ['relationship', 'You were never mine, but losing you broke me.', ''],
  ['relationship', 'Be the person you want to be with.', ''],
  ['relationship', 'There is no perfect. There will always be struggle. You just have to pick who you want to struggle with.', ''],
  ['relationship', 'A good woman is an investment. An immature girl is a bill.', ''],
  ['relationship', 'Breaking someone\'s heart is as easy as throwing a rock at the ocean, but you\'ll never know how deep that rock will go.', ''],
  ['design', 'Good design is like a refrigerator. When it works, no one notices; when it doesn\'t, it sure stinks.', 'Irene Au'],
  ['design', 'The role of the designer is that of a good, thoughtful host anticipating the needs of his guests.', 'Charles Eames'],
  ['design', 'People ignore designs that ignore people.', 'Frank Chimero'],
  ['design', 'To design is to transform prose into poetry.', 'Paul Rand'],
  ['design', 'It is not enough that we build products that function and are usable. We also need to build products that bring joy and beauty to people\'s lives.', 'Don Norman'],
  ['design', 'Recognising the need is the primary condition for design.', 'Charles Eames'],
  ['design', 'The goal of a designer is to listen, observe, understand, empathise and glean insights that make the invisible visible.', 'Hillman Curtis'],
  ['design', 'If you think good design is expensive, you should look at the cost of bad design.', 'Ralf Speth'],
  ['design', 'Any product that needs a manual to work is broken.', 'Elon Musk'],
  ['design', 'If you make design about design, you\'re just stacking bowls, and that\'s not what bowls are for.', 'Frank Chimero'],
  ['design', 'Great design is a multi-layered relationship between human life and its environment.', 'Naoto Fukasawa'],
  ['human', 'Success doesn\'t measure a human being. Effort does.', ''],
  ['human', 'We are interested in others when they are interested in us.', 'Publilius Syrus'],
  ['human', 'If you argue and contradict, you may achieve a victory sometimes, but it will be an empty victory because you will never get your opponent\'s good will.', 'Dale Carnegie'],
  ['human', 'Hatred is never ended by hatred but by love, and a misunderstanding is never ended by an argument but by tact and a sympathetic desire to see the other person\'s viewpoint.', 'Buddha'],
  ['human', 'Imagination is the power that enables us to empathise with humans whose experiences we have never shared.', 'J. K. Rowling'],
  ['knowledge', 'You cannot teach a man anything; you can only help him find it within himself.', 'Galileo'],
  ['knowledge', 'Be wiser than other people if you can, but do not tell them so.', 'Lord Chesterfield'],
  ['knowledge', 'One thing only I know, and that is that I know nothing.', 'Socrates'],
  ['knowledge', 'Learn to use your emotions to think, not think with your emotions.', 'Robert Kiyosaki'],
  ['finance', 'If you find you have dug yourself into a hole, stop digging.', 'Robert Kiyosaki'],
  ['finance', 'Wealth is a person\'s ability to survive a number of days forward.', 'Robert Kiyosaki'],
  ['motivation', 'Winners are not afraid of losing. Failure is part of the process of success. People who avoid failure also avoid success.', 'Robert Kiyosaki'],
  ['finance', 'There is always risk, so learn to manage risk instead of avoiding it.', 'Robert Kiyosaki'],
  ['motivation', 'The easy road often becomes hard, and the hard road often becomes easy.', 'Robert Kiyosaki'],
  ['motivation', 'Comfort is a drug. Give a weak man regular comfort and he\'ll throw his ambitions out of the window. The comfort zone is where dreams go to die.', 'Henry Cavill'],
  ['motivation', 'When you\'re possessed by your goal, you\'ll do anything.', 'Tim Denning'],
  ['motivation', 'When you focus on how your work helps people, it\'s powerful inspiration that makes money motivation seem ridiculous.', 'Tim Denning'],
  ['movies', 'Sometimes you have to run before you can walk.', 'Tony Stark'],
  ['movies', 'Control can sometimes be an illusion. But sometimes you need illusions to gain control.', 'Elliot Alderson'],
  ['knowledge', 'An idea is one thing, execution is another.', 'Marco Pierre White'],
  ['funny', 'You can ask me anything, but whether you get an answer is another question.', ''],
  ['stoic', 'It is not death we should fear. It is fearing that we never truly began living at all.', 'Marcus Aurelius'],
  ['motivation', 'Everything you want is on the other side of fear.', ''],
  ['relationship', 'Some people can stay in your heart but not in your life, because sometimes you have to forget what you feel and remember what you deserve.', ''],
  ['motivation', 'A man becomes a slave to anything he can\'t walk away from. Conquer yourself first.', ''],
  ['motivation', 'From the time you take your first breath, you become eligible to die.', 'David Goggins'],
  ['knowledge', 'Human beings change through study, habit and stories.', 'David Goggins'],
  ['knowledge', 'If you focus too far in front of you, you won\'t see the shiny thing out of the corner of your eye.', ''],
  ['motivation', 'Better to regret the things you\'ve done than the things you haven\'t.', ''],
  ['motivation', 'Men do what they must; fools do what they want.', 'Kevin Gates'],
  ['motivation', 'At your highest moment, be careful. That\'s when the devil comes for you.', 'Denzel Washington'],
  ['human', 'Respect people\'s time if you want to be respected.', ''],
  ['motivation', 'The goal in life is not to live forever, but to create something that will.', 'Juice WRLD'],
  ['motivation', 'Time flows constantly. It doesn\'t care about the people who are struggling.', ''],
  ['motivation', 'Never apologise for trying hard. It\'s an insult to your determination.', 'Might Guy'],
  ['motivation', 'Without struggle there\'s no progress.', 'Mike Tyson'],
  ['knowledge', 'No tree can grow to heaven unless its roots reach down to hell.', 'Carl Jung'],
];

export const BUILT_IN: Quote[] = [...RAW, ...MINE].map(([category, text, author], i) => ({
  id: `${category}-${i}`,
  text,
  author: author || 'Unknown',
  category,
}));

export function parseCustom(raw: string | null): Quote[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter(q => q && typeof q.text === 'string' && q.text.trim())
      .slice(0, 100)
      .map((q, i) => ({
        id: `custom-${i}`,
        text: String(q.text).trim(),
        author: typeof q.author === 'string' && q.author.trim() ? String(q.author).trim() : 'Unknown',
        category: 'custom' as const,
      }));
  } catch {
    return [];
  }
}

export function pickDeck(all: Quote[], categories: Category[], favouritesOnly: boolean, favourites: Set<string>) {
  const byCategory = all.filter(q => categories.includes(q.category));
  const deck = favouritesOnly ? byCategory.filter(q => favourites.has(q.id)) : byCategory;
  // an empty selection would leave nothing to show at all, so fall back rather than blank the screen
  return deck.length > 0 ? deck : byCategory.length > 0 ? byCategory : all;
}
